### ISSUE TITLE
sacmodel_line coefficient

### ISSUE THREAD

**Issue by ywfwyht** [xmba15/ransac_lines_fitting_gpu#1]
Hi bro! what are the coefficients of the sacmodel_line?  I don't understand and how to solve it.

pcl::ModelCoefficients::Ptr coeffs(new pcl::ModelCoefficients);
coeffs->values.reserve(6);
std::copy(cudaLineSegment.coeffs.p.begin(), cudaLineSegment.coeffs.p.end(), std::back_inserter(coeffs->values));
std::copy(cudaLineSegment.coeffs.d.begin(), cudaLineSegment.coeffs.d.end(), std::back_inserter(coeffs->values));

 perception::cuda::LineSegment lineSegment;
lineSegment.coeffs.p = {hostCoeffs.p.x, hostCoeffs.p.y, 0};
lineSegment.coeffs.d = {hostCoeffs.d.x, hostCoeffs.d.y, 0};
lineSegment.inlierIndices = std::move(hostInlierIndicesV[i]);
result.emplace_back(std::move(lineSegment));

**Comment by xmba15** [comment]
Hi @ywfwyht, the coefficients of 3d lines are x,y,z,vx,vy,vz ((x,y,z) is a point on line and (vx,vy,vz) is direction vector)
Same for 2d lines. Coeffs are x,y,vx,vy

**Comment by ywfwyht** [comment]
ok!  how to get the  x,y,z,vx,vy,vz ? are you chinese? if you are,  we can communicate in chinese.

**Comment by xmba15** [comment]
Hi @ywfwyht Sorry, I cannot speak Chinese.

The method here is just conventional RANSAC model fitting. 
Here is a lecture slide about the details.
https://cs.gmu.edu/~kosecka/cs482/lect-fitting.pdf

This repo only further extends the conventional RANSAC into GPU computing. I guess the easy way to understand is first implementing the algorithm yourself in a simpler language like python, or C++(without GPU).

**Comment by ywfwyht** [comment]
Thanks very much!
