### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by rsleishaui** [xmba15/ransac_lines_fitting_gpu#3]
Hello, I want to convert this code to the windows system, but in the sacmodel code of cuda, the array is out of bounds, in these two lines，请问您知道怎么回事吗
            samples.x = indices[(int)(rng() * trand)];
            samples.y = indices[(int)(rng() * trand)];

**Comment by xmba15** [comment]
I can't promise that I could help much with this now as I am busy. But if you don't mind, can you share the point cloud data you tested and failed?

**Comment by rsleishaui** [comment]
Thank you, I have solved the problem because I wanted to test on the Windows system and the macro value was inconsistent with the Linux system.
